[pytest]
addopts =
    --ignore=tests/test_lnchannel.py
    --ignore=tests/test_lnhtlc.py
    --ignore=tests/test_lnmsg.py
    --ignore=tests/test_lnpeer.py
    --ignore=tests/test_lnpeermgr.py
    --ignore=tests/test_lnrouter.py
    --ignore=tests/test_lntransport.py
    --ignore=tests/test_lnurl.py
    --ignore=tests/test_lnutil.py
    --ignore=tests/test_lnwallet.py
    --ignore=tests/test_bolt11.py
    --ignore=tests/test_mpp_split.py
    --ignore=tests/test_onion_message.py
